### ISSUE TITLE
InstanceRefer(xyz): Acc@0.5IoU 37.05 

### ISSUE THREAD

**Issue by bwittmann** [CurryYuan/InstanceRefer#5]
I am currently having a look at the performance of your architecture. In the paper you state that the Acc@0.5IoU is **37.05** using only xyz coordinates which is way higher than the Acc@0.5IoU of **30.70** using additional color information. Is this just a typo in the paper or is the additional rgb information really damaging your performance? If this is a typo, could you please provide me with the correct Acc@0.5IoU results?

Thank you very much!

**Comment by CurryYuan** [comment]
Hi @bwittmann,

This is a typo, it should be 27.05 using only xyz coordinates. Color information is important. We will upload a revised version of our paper recently.

Best
