### ISSUE TITLE
different performance in your paper and released log

### ISSUE THREAD

**Issue by Umaruchain** [CurryYuan/InstanceRefer#6]
there is difference   between your paper and released log.
Is this because of your model difference or the way of training?

**Comment by yanx27** [comment]
![image](https://user-images.githubusercontent.com/35829331/125330768-bc9ebe00-e379-11eb-8015-75d28fd91c4a.png)
We only release the model using xyz+rgb as inputs. It 's the same.

**Comment by Umaruchain** [comment]
Thanks a lot!
