### ISSUE TITLE
the resulrt of pretrained model I run is differnet from yours

### ISSUE THREAD

**Issue by Umaruchain** [CurryYuan/InstanceRefer#7]
I follow your instructions and run your pretrained model.
But the eval result is 
iou0.25: 0.3751
iou0.5: 0.3056
I do not know why it is different form yours.
Thank you very much!

**Comment by yanx27** [comment]
Hi @Umaruchain , thanks for your attention. I think your results are the same as ours (37.57/30.70). The slight difference might be caused by randomness or different libraries version. You can try again and obtain different results.

**Comment by Umaruchain** [comment]
thank you so much.
Also I train  single ap module. only use the score of attribute and change the gamma from 5 -> 15 since the score is limited to (-1,1).
And the result is much better than your paper result ， it is confusing.
best.

**Comment by yanx27** [comment]
@Umaruchain It is strange, what's your result?

**Comment by Umaruchain** [comment]
xyz + rgb
0.25 : 0.3549
0.5 : 0.2888

**Comment by yanx27** [comment]
Hi, these results are tested with `xyz+rgb+normal` in old paper, please see our updated paper:)
