### ISSUE TITLE
An error when loading data

### ISSUE THREAD

**Issue by vivonicole** [CurryYuan/InstanceRefer#8]
Thank you for this amazing work.

When I run "python scripts/train.py --log_dir instancerefer", I encountered a problem:

  File "/home/nicole/InstanceRefer/lib/dataset.py", line 184, in __getitem__
    class_ind = [DC.nyu40id2class[int(x)] for x in instance_bboxes[:num_bbox, -2]]
  File "/home/nicole/InstanceRefer/lib/dataset.py", line 184, in <listcomp>
    class_ind = [DC.nyu40id2class[int(x)] for x in instance_bboxes[:num_bbox, -2]]
KeyError: 0

the x is 0.0 but DC.nyu40id2class does not contain 0. Should I modify the code as "DC.nyu40id2class[int(x)+1]"?

**Comment by vivonicole** [comment]
Sorry. this problem is caused by I forgot the _vh_clean.aggregation.json data.

**Comment by ayushjain1144** [comment]
@vivonicole Hi, I am facing the same error, could you please let me know how exactly you fixed it? Which file is this?

**Comment by haoranD** [comment]
> Thank you for this amazing work.
> 
> When I run "python scripts/train.py --log_dir instancerefer", I encountered a problem:
> 
> File "/home/nicole/InstanceRefer/lib/dataset.py", line 184, in **getitem** class_ind = [DC.nyu40id2class[int(x)] for x in instance_bboxes[:num_bbox, -2]] File "/home/nicole/InstanceRefer/lib/dataset.py", line 184, in class_ind = [DC.nyu40id2class[int(x)] for x in instance_bboxes[:num_bbox, -2]] KeyError: 0
> 
> the x is 0.0 but DC.nyu40id2class does not contain 0. Should I modify the code as "DC.nyu40id2class[int(x)+1]"?

Hi, I also got the same error. Could you please share more details on how you solve it?
Thanks a lot.

**Comment by xukujiu** [comment]
> > Thank you for this amazing work.
> > When I run "python scripts/train.py --log_dir instancerefer", I encountered a problem:
> > File "/home/nicole/InstanceRefer/lib/dataset.py", line 184, in **getitem** class_ind = [DC.nyu40id2class[int(x)] for x in instance_bboxes[:num_bbox, -2]] File "/home/nicole/InstanceRefer/lib/dataset.py", line 184, in class_ind = [DC.nyu40id2class[int(x)] for x in instance_bboxes[:num_bbox, -2]] KeyError: 0
> > the x is 0.0 but DC.nyu40id2class does not contain 0. Should I modify the code as "DC.nyu40id2class[int(x)+1]"?
> 
> Hi, I also got the same error. Could you please share more details on how you solve it? Thanks a lot.

Hi, I also got the same error. Could you please share more details on how you solve it?
Thanks a lot.
